export const BID_LIST_REQUEST = 'BID_LIST_REQUEST'
export const BID_LIST_SUCCESS = 'BID_LIST_SUCCESS'
export const BID_LIST_FAIL = 'BID_LIST_FAIL'

export const CREATE_BID_REQUEST = 'CREATE_BID_REQUEST'
export const CREATE_BID_SUCCESS = 'CREATE_BID_SUCCESS'
export const CREATE_BID_FAIL = 'CREATE_BID_FAIL'