export const FUND_REQUEST = 'FUND_REQUEST'
export const FUND_SUCCESS = 'FUND_SUCCESS'
export const FUND_FAIL = 'FUND_FAIL'

export const CREATE_FUND_REQUEST = 'CREATE_FUND_REQUEST'
export const CREATE_FUND_SUCCESS = 'CREATE_FUND_SUCCESS'
export const CREATE_FUND_FAIL = 'CREATE_FUND_FAIL'
